#ROSALIND BIOINFORMATICS PROBLEMS
#http://rosalind.info/problems/dna/

def count_nucleotids(dna_sequence):
    A = 0
    G = 0
    C = 0
    T = 0

    for nucleotide in dna_sequence:
        if nucleotide == 'A':
            A += 1
        if nucleotide == 'G':
            G += 1
        if nucleotide == 'C':
            C += 1
        if nucleotide == 'T':
            T += 1
    return A, C, G, T

A, C, G, T = count_nucleotids('CTTACTCCTCCAGACACGCCTGAAATCCATTGCTCAGAGACCGCCTGTTTGGCTCATATCGATGGCCCACTGTAGAGGTAAGCTCGAATTTTGAGACCAAACGGCATGGCAGTGTGTTAACATCCTTGTTGACGCGATGTCGAGGATCTTAATTTACCAGCTCATAAAGTATGAAATATAGCACTAGTTAAGATATTAAACCTCGGCGTTGAAGTAGCGCCGATTGACGAAATTAGCGTGGAGAGCAATGACACAGCGCATCGGTAAAGGTATCCATGGACAGGGAATCCGAAACTTCTAGTTTTGCCACTCGGCTCTACAATGACGGTGTAGTCTCGTCCTCACGGCATGTCGTGGGTAAATCACAGGTTTCGGTTAGTTAAGGATCAGTGTCGCTGACCGACTCGTGGACTCTATTCTCTTTCAAGAGCAGAGGAGGTCACACGGCACTAATAACACAAGTGGCGCTTTAGATATCAATGGCGTTCGCGTCTGATATTTGCCGGAATGCCGCCTCACATGTCACTCTTAGAATCTTGCCGCTAGCTGAAACTTCTCTCGTAACAAGCCTAAAATATCGTCCTTGCTAACTCCATCCTAATGCAAGTCCGTACATGAAAGCAACTAATCGCACTGGCTCCACACTGGGCCAGATCCAGGGCCGCAATTCTGAGCTTAGTGCCCCGGTATAACCCACGTTGTGTATGCAATTCTTGAGCTCCGATCGGTTTCAAACTGGTCGCATACCTGTATACGGCTTGAAGGCTCTCATCGATAGATATTGTGGAGAACACGAGGATGTCATTCACCACGGTATTGGCAATTATCGCGGCAGGCGTCTATTTTTCTCGTCCTTCACTTGGGACCGGACTATTAAAAAGGGGGACCAAAGCGGACGCTTATAGGTCACGGTAAAACAATCCCTGAAAAGGCCACGTAGCACGGGTTAGAGGAGCTGATCCCTGATGGAGTCTC')
print(A, C, G, T)