#ROSALIND BIOINFORMATICS PROBLEMS
#http://rosalind.info/problems/subs/

def find_motif(dna_sequence, motif):
    positions = []
    for i in range(len(dna_sequence)):
        if dna_sequence[i:i+len(motif)] == motif:
            positions.append(i+1)
    return positions

dna = 'CTAATGGTCTAATGGCTCGGATCTAATGGCTAATGGCCTAATGGCTACCTAATGGGATTGCTAATGGACTAATGGCTAATGGCATCCTAATGGTTTGAAAGACTAATGGTACCCTAATGGCTAATGGCCTAATGGCTCACCTAATGGCTAATGGCTAATGGCTAATGGCTACTAATGGCAGCGCTAATGGCTAATGGCTAATGGTGTTCTAATGGATGGGCGCAGCTAATGGCTAATGGGCTTGTTTTCTAATGGCGTCTAATGGCTAATGGCTAATGGACTAATGGGGGTCTAATGGCTAATGGACCCTAATGGCCACTAATGGCGGCCTAATGGGACTAATGGCAGGTCTAATGGACCTAATGGCCTAATGGCTCTAATGGCTCGGGCTAATGGGCCGTACGGGAGCTAATGGCATACGAGCTAATGGTACTAATGGCTAATGGGCTAATGGCTAATGGATCCGCATGGTATGCTAATGGTCTAATGGCTAATGGACGCTAATGGCCACTAATGGACTAATGGTCCTAATGGAGGCTAATGGCCTAATGGACTAATGGGCTAATGGCTAATGGTCTAATGGCTAATGGTCTAATGGGCTAATGGGCTAATGGGGCTAATGGCTAATGGCTAATGGCTAATGGCTCTTATACACTAATGGTCGCCTAATGGCTTATGACACTAATGGTCTAATGGCTAATGGTTGGATTTACTAATGGTTTGGCTAATGGCAGGTTCTAATGGCGGGCTAATGGACCTCTAATGGCACTAATGGAGCGCTAAACCTCTAATGGTTGTATACACAGAAGGCCTAATGGCTAATGGCTAATGGCTAATGGACTCTAATGGCGTCCTAATGGCCTGCTAATGGCTAATGGCTAATGGCTAATGGAGGGCTAATGGACGTCTAATGGCTAATGGCTAATGGACTAATGGCCTAATGGGATCTGACGATCCGATATGCTAATGG'
sub = 'CTAATGGCT'

print(find_motif(dna, sub))
#LOGS [9, 23, 38, 69, 114, 129, 141, 148, 155, 162, 184, 191, 226, 259, 266, 292, 368, 377, 433, 448, 484, 562, 577, 617, 624, 631, 638, 666, 690, 812, 819, 826, 865, 872, 879, 908, 915]